#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 11 12:10:39 2020

@author: joshi
"""

class Test:
    def __init__(self):
       self.test_val = 1
    def ret_val(self):
        return self.test_val
a = Test
print(a.ret_val(0))